---
###############################################################################
# Helm CLI Installation Defaults
###############################################################################

# Helm binary location
helm_binary_dest: /usr/local/bin/helm


# Temporary download location
helm_install_tmp_dir: /tmp/helm-install


# Required Helm version
# Keep this pinned for production stability
helm_version: v3.15.4