---
plugin: amazon.aws.aws_ec2


regions:

  - ap-southeast-1



filters:

  instance-state-name: running

  tag:Project: "k8s"

  tag:Environment: "pr"



compose:

  ansible_host: private_ip_address


  node_name: tags.Node | regex_replace('-','_')


  role_name: tags.Role | regex_replace('-','_')



keyed_groups:


  - key: tags.Role

    prefix: raw

    separator: "_"



  - key: tags.Environment

    prefix: env

    separator: "_"



strict: false



cache: true

cache_plugin: jsonfile

cache_connection: .ansible_cache/aws_ec2

cache_timeout: 300

cache_prefix: aws_ec2