---
plugin: amazon.aws.aws_ec2

regions:
  - ap-southeast-1

filters:
  instance-state-name: running
  tag:Project: "k8s"
  tag:Environment: "pr"

hostnames:
  - instance-id

compose:
  ansible_host: private_ip_address

  node_name: ec2_tags.Node | default("")
  role_name: ec2_tags.Role | default("")
  cluster_name: ec2_tags.Cluster | default("")

  instance_id: instance_id
  instance_name: ec2_tags.Name | default("")
  private_ip: private_ip_address
  public_ip: public_ip_address | default("")
  private_dns: private_dns_name | default("")
  public_dns: public_dns_name | default("")

  availability_zone: placement.availability_zone
  region: placement.region | default("ap-southeast-1")

  vpc_id: vpc_id
  subnet_id: subnet_id

  image_id: image_id
  instance_type: instance_type
  architecture: architecture

  project: ec2_tags.Project | default("")
  environment_name: ec2_tags.Environment | default("")
  cluster: ec2_tags.Cluster | default("")
  role: ec2_tags.Role | default("")
  bootstrap: ec2_tags.Bootstrap | default("false")
  managed_by: ec2_tags.ManagedBy | default("")
  owner: ec2_tags.Owner | default("")

groups:
  control_plane: ec2_tags.Role == "control-plane"
  worker: ec2_tags.Role == "worker"
  bootstrap: ec2_tags.Bootstrap == "true"
  jenkins: ec2_tags.Role == "jenkins"

strict: false

cache: true
cache_plugin: jsonfile
cache_connection: .ansible_cache/aws_ec2
cache_timeout: 300
cache_prefix: aws_ec2