---
plugin: amazon.aws.aws_ec2


regions:

  - ap-southeast-1



filters:

  instance-state-name: running

  tag:Project: "k8s"

  tag:Environment: "pr"



compose:

  ansible_host: private_ip_address


  node_name: tags.Node | regex_replace('-','_')


  role_name: tags.Role | regex_replace('-','_')



<<<<<<< HEAD
groups:
  control_plane: tags.Role == "control-plane"
  worker: tags.Role == "worker"
  bootstrap: tags.Bootstrap == "true"
  jenkins: tags.Role == "jenkins"
  env_pr: tags.Environment == "pr"
=======
keyed_groups:


  - key: tags.Role

    prefix: raw

    separator: "_"



  - key: tags.Environment

    prefix: env

    separator: "_"

>>>>>>> 7f1709627deb16d4c30f614a1cb820aaa6a2e1e6


strict: false



cache: true

cache_plugin: jsonfile

cache_connection: .ansible_cache/aws_ec2

cache_timeout: 300

cache_prefix: aws_ec2