---

- name: Create monitoring configuration directory

  ansible.builtin.file:

    path: /etc/kubernetes/monitoring

    state: directory

    mode: "0755"



- name: Create Prometheus values

  ansible.builtin.template:

    src: kube-prometheus-stack.yaml.j2

    dest: /etc/kubernetes/monitoring/prometheus.yaml

    mode: "0644"



- name: Create Loki values

  ansible.builtin.template:

    src: loki.yaml.j2

    dest: /etc/kubernetes/monitoring/loki.yaml

    mode: "0644"



- name: Create Promtail values

  ansible.builtin.template:

    src: promtail.yaml.j2

    dest: /etc/kubernetes/monitoring/promtail.yaml

    mode: "0644"