###############################################################################
# Join Control Plane Defaults
###############################################################################

join_marker_path: /etc/kubernetes/.ansible-join-complete

join_admin_conf_path: /etc/kubernetes/admin.conf


###############################################################################
# Local Artifacts
###############################################################################

control_plane_join_command_path: "{{ local_artifacts_dir }}/control-plane-join-command.sh"


###############################################################################
# AWS SSM
###############################################################################

kubeadm_control_plane_join_parameter: ""

kubeadm_certificate_key_parameter: ""


###############################################################################
# Wait
###############################################################################

join_ready_wait_retries: 30

join_ready_wait_delay: 10


###############################################################################
# etcd
###############################################################################

join_etcd_wait_retries: 18

join_etcd_wait_delay: 10


###############################################################################
# Recovery
###############################################################################

join_use_ssm_fallback: true