---
###############################################################################
# Kubernetes Cluster
###############################################################################

kubernetes_version: "1.30.14"

kubernetes_apt_series: "1.30"

###############################################################################
# Control Plane
###############################################################################

control_plane_endpoint: "{{ hostvars[groups['bootstrap_true'][0]].ansible_host }}"

control_plane_endpoint_port: 6443

###############################################################################
# Container Runtime
###############################################################################

containerd_socket: "unix:///run/containerd/containerd.sock"

crictl_config_file: "/etc/crictl.yaml"