---
###############################################################################
# Install Helm CLI
###############################################################################

- name: Install Helm binary
  ansible.builtin.include_tasks:
    install_helm_binary.yml