###############################################################################
# Worker Join Defaults
###############################################################################


worker_join_marker_path: /etc/kubernetes/.ansible-join-complete


###############################################################################
# Local Artifact
###############################################################################

worker_join_command_path: "{{ local_artifacts_dir }}/worker-join-command.sh"



###############################################################################
# AWS SSM fallback
###############################################################################

worker_join_ssm_parameter: ""

worker_join_use_ssm_fallback: true



###############################################################################
# Readiness
###############################################################################

worker_ready_wait_retries: 30

worker_ready_wait_delay: 10



###############################################################################
# Control Plane kubeconfig
###############################################################################

worker_admin_conf_path_on_control_plane: /etc/kubernetes/admin.conf