
validation_admin_conf_path: /etc/kubernetes/admin.conf

validation_fail_fast: true

validation_coredns_min_ready: 1

validation_required_static_pods:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - etcd

validation_monitoring_namespace: monitoring

validation_monitoring_deployments:
  - kube-prometheus-stack-grafana
  - kube-prometheus-stack-operator
  - kube-prometheus-stack-kube-state-metrics

validation_monitoring_statefulsets:
  - prometheus-kube-prometheus-stack-prometheus
  - alertmanager-kube-prometheus-stack-alertmanager
  - loki

validation_monitoring_daemonsets:
  - promtail





validation_required_namespaces:
  - argocd
  - ingress-nginx
  - cert-manager
  - kube-system
  - monitoring

validation_required_deployments:
  - argocd/argocd-server
  - ingress-nginx/ingress-nginx-controller
  - cert-manager/cert-manager

validation_required_daemonsets:
  - kube-system/aws-ebs-csi-node

