---
- name: Get current hostname
  ansible.builtin.command: hostname
  register: hostname_result
  changed_when: false

- name: Assert hostname matches Terraform Node tag
  ansible.builtin.assert:
    that:
      - hostname_result.stdout == ec2_tags.Node
    fail_msg: "Hostname does not match Terraform Node tag."
    success_msg: "Hostname matches Terraform Node tag."