---
- name: Join Remaining Control Plane Nodes
  hosts: control_plane:!bootstrap
  become: true
  gather_facts: true
  any_errors_fatal: true
  serial: 1

  vars_files:
    - vars/defaults.yml
    - vars/terraform.yml
    - vars/kubernetes.yml
    - vars/containerd.yml
    - vars/calico.yml
    - vars/helm.yml
    - vars/validation.yml
    - vars/artifacts.yml

  roles:
    - role: join_control_plane
      tags:
        - join-control-plane