---
- name: Install Calico CNI
  hosts: bootstrap
  become: true
  gather_facts: true
  any_errors_fatal: true

  vars_files:
    - "{{ playbook_dir }}/../vars/defaults.yml"
    - "{{ playbook_dir }}/../vars/terraform.yml"
    - "{{ playbook_dir }}/../vars/kubernetes.yml"
    - "{{ playbook_dir }}/../vars/containerd.yml"
    - "{{ playbook_dir }}/../vars/calico.yml"
    - "{{ playbook_dir }}/../vars/helm.yml"
    - "{{ playbook_dir }}/../vars/validation.yml"
    - "{{ playbook_dir }}/../vars/artifacts.yml"

  roles:
    - role: install_cni
      tags:
        - cni