---

- name: Wait until every cluster node becomes Ready
  ansible.builtin.command:
    cmd: >-
      kubectl
      --kubeconfig={{ admin_kubeconfig_path }}
      wait
      --for=condition=Ready
      nodes
      --all
      --timeout=300s
  register: nodes_ready
  changed_when: false

- name: Show node status
  ansible.builtin.command:
    cmd: >-
      kubectl
      --kubeconfig={{ admin_kubeconfig_path }}
      get nodes
      -o wide
  register: node_status
  changed_when: false

- name: Display node status
  ansible.builtin.debug:
    var: node_status.stdout_lines