---
###############################################################################
# Control Plane Variables
###############################################################################

node_role: control_plane

###############################################################################
# kubectl
###############################################################################

kubectl_expected: true

###############################################################################
# Kubernetes Directories
###############################################################################

kubernetes_directory: /etc/kubernetes

kubernetes_manifest_directory: /etc/kubernetes/manifests

kubernetes_pki_directory: /etc/kubernetes/pki

admin_conf_path: /etc/kubernetes/admin.conf

###############################################################################
# Bootstrap
###############################################################################

bootstrap_group: bootstrap

###############################################################################
# etcd
###############################################################################

etcd_health_endpoint: https://127.0.0.1:2379

etcd_ca_file: /etc/kubernetes/pki/etcd/ca.crt

etcd_cert_file: /etc/kubernetes/pki/etcd/healthcheck-client.crt

etcd_key_file: /etc/kubernetes/pki/etcd/healthcheck-client.key

###############################################################################
# Validation Ports
###############################################################################

control_plane_ports:

  - 6443

  - 2379

  - 2380

  - 10250

  - 10257

  - 10259