---
###############################################################################
# Worker Variables
###############################################################################

node_role: worker

###############################################################################
# kubectl
###############################################################################

# Workers do not require kubectl in the Golden AMI.
kubectl_expected: false

###############################################################################
# Kubelet
###############################################################################

kubelet_directory: /var/lib/kubelet

kubelet_config_file: /var/lib/kubelet/config.yaml

kubeadm_flags_file: /var/lib/kubelet/kubeadm-flags.env

###############################################################################
# Container Runtime
###############################################################################

container_runtime_endpoint: unix:///run/containerd/containerd.sock

###############################################################################
# Worker Join
###############################################################################

worker_join_batch: "30%"

###############################################################################
# NodePort Range
###############################################################################

nodeport_range:

  start: 30000

  end: 32767

###############################################################################
# Validation Ports
###############################################################################

worker_ports:

  - 10250

###############################################################################
# Expected Labels
###############################################################################

expected_worker_labels:

  - node-role.kubernetes.io/worker